import { Header, JobList } from "@/features";
import ListSidebar from "@/page-components/ListSidebar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main>
        <section>
          <Header />
          <div className="lg:grid lg:grid-cols-[2fr_10fr] lg:gap-8 mt-11">
            <ListSidebar className="mb-5" />
            <JobList />
          </div>
        </section>
      </main>
    </>
  );
}
